### ISSUE TITLE
Versioning too strict

### ISSUE THREAD

**Issue by andreped** [dbouget/raidionics_seg_lib#3]
It would be better if this backend didn't have such strict versioning on the dependencies.

For instance, I have problems using this backend on Python 3.8 on macOS 13.0, as there does not exist any precompiled wheels for the current Pandas version (see [here](https://github.com/dbouget/raidionics_seg_lib/blob/master/requirements.txt#L3)), which is also quite old.

You should likely add cross-platform, cross-python version tests to verify which setup works for most relevant setups. For instance, see [here](https://github.com/andreped/GradientAccumulator/blob/main/.github/workflows/test.yml#L51) for how I made CI checks for various setups for the GradientAccumulator repo.

**Comment by dbouget** [comment]
Running some tests on the update branch with different Python versions, might add different OS versions after that. But yeah, putting a "loose" versioning seems to work here, let's see how it goes down the line with Raidionics...

**Comment by dbouget** [comment]
Can be considered closed from this commit f4120467d22afb612c7badaecffffbb2c75cfd4a
The new wheel from v1.2.1 on should cover more Python and OS versions.
